version: "2"

services:
  db:
    container_name: database
    image: "yandex/clickhouse-server:latest"
    restart: always
    network_mode: default
    ports:
    - "9000:9000"
    mem_limit: 4g
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    tty: true
    volumes: []
    environment: {}
